### ISSUE TITLE
BackEnd: Initiate Project Folder Structure.

### ISSUE THREAD

**Issue by magdykashef** [magdykashef/ecommerce#8]

**Comment by Ahmed-ELking** [comment]
I have made a pull request with branch name iss-8.

**Comment by Ahmed-ELking** [comment]
Hi Magdy,
I have assigned these properties to return from the creation of a new user:-
use_id
user_name
status
role
token

**Comment by Ahmed-ELking** [comment]
Hi, Magdy
I have finished the back-end initialization structure and you can accept the pull request.
